import CMigemoC
import Foundation

/// Errors thrown by ``Migemo`` APIs.
public enum MigemoError: Error, Sendable, Equatable {
    /// The dictionary file does not exist at the given path.
    case dictionaryNotFound(path: String)
    /// The dictionary file exists but could not be loaded by cmigemo.
    case dictionaryLoadFailed(path: String)
    /// The query string is empty.
    case emptyQuery
    /// cmigemo failed to generate a pattern for the given query.
    case queryFailed
    /// The generated pattern could not be decoded as UTF-8.
    case invalidPatternEncoding
}

/// Dictionary source used by ``Migemo``.
public enum DictionarySource: Sendable {
    /// Use the dictionary bundled in this Swift package.
    case bundled
    /// Use a custom dictionary directory that contains `migemo-dict` and companion `.dat` files.
    case directory(URL)
}

/// Options used to initialize ``Migemo``.
public struct MigemoOptions: Sendable {
    /// Dictionary source to use for pattern generation.
    public var dictionary: DictionarySource

    /// Creates initialization options.
    /// - Parameter dictionary: Dictionary source. Defaults to `.bundled`.
    public init(dictionary: DictionarySource = .bundled) {
        self.dictionary = dictionary
    }
}

/// Swift wrapper around the vendored cmigemo C library.
public final class Migemo {
    private let handle: OpaquePointer

    /// Creates a Migemo instance with the specified options.
    /// - Parameter options: Initialization options. Defaults to bundled dictionary assets.
    /// - Throws: ``MigemoError`` when dictionary loading fails.
    public convenience init(options: MigemoOptions = .init()) throws {
        try self.init(dictionaryPath: Self.dictionaryPath(for: options.dictionary))
    }

    /// Creates a Migemo instance from an explicit `migemo-dict` file path.
    /// - Parameter dictionaryPath: Full path to `migemo-dict`.
    /// - Throws: ``MigemoError`` when the file is missing or cannot be loaded.
    public init(dictionaryPath: String) throws {
        guard FileManager.default.fileExists(atPath: dictionaryPath) else {
            throw MigemoError.dictionaryNotFound(path: dictionaryPath)
        }
        guard let handle = migemo_open(dictionaryPath) else {
            throw MigemoError.dictionaryLoadFailed(path: dictionaryPath)
        }
        guard migemo_is_enable(handle) != 0 else {
            migemo_close(handle)
            throw MigemoError.dictionaryLoadFailed(path: dictionaryPath)
        }
        self.handle = handle
    }

    deinit {
        migemo_close(handle)
    }

    /// Generates a regular-expression pattern from a romanized query.
    /// - Parameter query: Romanized query text such as `"kensaku"`.
    /// - Returns: A regex pattern string generated by cmigemo.
    /// - Throws: ``MigemoError`` when query validation or generation fails.
    public func regexPattern(for query: String) throws -> String {
        guard !query.isEmpty else {
            throw MigemoError.emptyQuery
        }

        var queryBytes = Array(query.utf8)
        queryBytes.append(0)

        return try queryBytes.withUnsafeBufferPointer { buffer in
            guard let queryPointer = buffer.baseAddress else {
                throw MigemoError.queryFailed
            }
            guard let result = migemo_query(handle, queryPointer) else {
                throw MigemoError.queryFailed
            }
            defer {
                migemo_release(handle, result)
            }

            let cString = UnsafeRawPointer(result).assumingMemoryBound(to: CChar.self)
            guard let pattern = String(validatingCString: cString) else {
                throw MigemoError.invalidPatternEncoding
            }
            return pattern
        }
    }

    /// Generates and compiles a Swift `Regex` from a romanized query.
    /// - Parameter query: Romanized query text.
    /// - Returns: Compiled `Regex<AnyRegexOutput>`.
    /// - Throws: ``MigemoError`` when generation fails or regex compilation throws.
    @available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
    public func regex(for query: String) throws -> Regex<AnyRegexOutput> {
        try Regex(try regexPattern(for: query))
    }

    private static func dictionaryPath(for source: DictionarySource) throws -> String {
        switch source {
        case .bundled:
            guard let url = Bundle.module.url(
                forResource: "migemo-dict",
                withExtension: nil
            ) else {
                throw MigemoError.dictionaryNotFound(path: "Bundle.module/migemo-dict")
            }
            return url.path
        case .directory(let directoryURL):
            return directoryURL.appendingPathComponent("migemo-dict").path
        }
    }
}
